###
POST https://localhost:5001/api/produto/create
Content-Type: application/json

{
    "Nome" : "Arroz",
    "Preco": 20.5
}

###
GET https://localhost:5001/api/produto/list

###
GET https://localhost:5001/api/produto/getbyid/1

###
DELETE https://localhost:5001/api/produto/delete/Bolacha

###
DELETE https://localhost:5001/api/produto/delete/1

###
PUT https://localhost:5001/api/produto/update
Content-Type: application/json

{   
    "Id": 1,
    "Nome" : "Bolacha alterada",
    "Preco": 3.60
}
