###
POST https://localhost:5001/api/produto/create
Content-Type: application/json

{
    "Nome" : "Camisa",
    "Preco": 150.5,
    "Descricao": "teste",
    "Quantidade": 10,
    "CategoriaId": 3
    
}

###
GET https://localhost:5001/api/produto/list

###
GET https://localhost:5001/api/produto/getbyid/7

###
DELETE https://localhost:5001/api/produto/delete/Bolacha

###
DELETE https://localhost:5001/api/produto/delete/8

###
PUT https://localhost:5001/api/produto/update
Content-Type: application/json

{   
    "Id": 7,
    "Nome" : "Camisa",
    "Preco": 150.60,
    "CategoriaId": 1
}
